---
- name: Loading configurations
  hosts: localhost
  tasks:
    - name: Read existing JSON file for UERANSIM
      slurp:
        path: "{{ playbook_dir }}/cfg/ue_cfg.json"
      register: json_content

    - name: Decode JSON content for UERANSIM
      set_fact:
        decoded_json_ue: "{{ json_content.content | b64decode | from_json }}"

    - name: Read existing JSON file for UPF
      slurp:
        path: "{{ playbook_dir }}/cfg/data_cfg.json"
      register: json_content

    - name: Decode JSON content for UPF
      set_fact:
        decoded_json_upf: "{{ json_content.content | b64decode | from_json }}"

    - name: Read existing JSON file for control
      slurp:
        path: "{{ playbook_dir }}/cfg/control_cfg.json"
      register: json_content

    - name: Decode JSON content for control
      set_fact:
        decoded_json_control: "{{ json_content.content | b64decode | from_json }}"

- name: Loading configurations for UE
  hosts: ue
  tasks:
    - name: Generate GNB config
      vars:
        gtpIp: "{{ hostvars['localhost']['decoded_json_ue']['wg0'] }}"
        ngapIp: "{{ hostvars['localhost']['decoded_json_ue']['wg0'] }}"
        amfIp: "{{ hostvars['localhost']['decoded_json_control']['wg0'] }}"

      template:
        src: "{{playbook_dir}}/nf_cfg/free5gc-gnb.yaml.j2"
        dest: "{{ansible_user_dir}}/UERANSIM/config/free5gc-gnb.yaml"


- name: Loading configurations for control
  hosts: control
  tasks:
    - name: Generate AMF config
      vars:
        ngapIp: "{{ hostvars['localhost']['decoded_json_control']['wg0'] }}"
      template:
        src: "{{playbook_dir}}/nf_cfg/amfcfg.yaml.j2"
        dest: "{{ansible_user_dir}}/free5gc/config/amfcfg.yaml"

    - name: Generate SMF config
      vars:
        upfIp: "{{ hostvars['localhost']['decoded_json_upf']['wg0'] }}"
        pfcpIp: "{{ hostvars['localhost']['decoded_json_control']['wg0'] }}"
      template:
        src: "{{playbook_dir}}/nf_cfg/smfcfg.yaml.j2"
        dest: "{{ansible_user_dir}}/free5gc/config/smfcfg.yaml"


- name: Loading configurations for control
  hosts: upf
  tasks:
    - name: Generate UPF config
      vars:
        gtpIp: "{{ hostvars['localhost']['decoded_json_upf']['wg0'] }}"
      template:
        src: "{{playbook_dir}}/nf_cfg/upfcfg.yaml.j2"
        dest: "{{ansible_user_dir}}/free5gc/config/upfcfg.yaml"
